[env]
extra_scripts =
    pre:hooks/auto_firmware_version.py

build_flags =
  -D DEBUG=0
  -D WAIT_FOR_SERIAL=0

[pico_base]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
lib_deps =
    smfsw/Queue@^2.0
    adafruit/Adafruit SSD1306@^2.5.13
    robtillaart/CRC@^1.0.3
build_flags =
  ${env.build_flags}
  -D PIN_SDA_XBOX=0 # GPIO00
  -D PIN_SCL_XBOX=1 # GPIO01
  -D PIN_SDA_DISP=6 # GPIO06
  -D PIN_SCL_DISP=7 # GPIO07
  -D SERIAL_BAUD=115200

[env:pico]
extends = pico_base
board = rpipico

[env:pico2]
extends = pico_base
board = rpipico2

[esp32_base]
platform = espressif32
framework = arduino
lib_deps =
    smfsw/Queue@^2.0
    adafruit/Adafruit SSD1306@^2.5.13
    robtillaart/CRC@^1.0.3

[env:esp32]
extends = esp32_base
board = esp32dev
build_flags =
  ${env.build_flags}
  -D PIN_SDA_XBOX=21 # GPIO21
  -D PIN_SCL_XBOX=22 # GPIO22
  -D PIN_SDA_DISP=18 # GPIO18
  -D PIN_SCL_DISP=19 # GPIO19
  -D SERIAL_BAUD=115200

[env:esp32s3]
extends = esp32_base
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -D PIN_SDA_XBOX=8  # GPIO08
  -D PIN_SCL_XBOX=9  # GPIO09
  -D PIN_SDA_DISP=4  # GPIO04
  -D PIN_SCL_DISP=5  # GPIO05
  -D SERIAL_BAUD=115200

[teensy_base]
platform = teensy
framework = arduino
lib_deps =
    smfsw/Queue@^2.0
    adafruit/Adafruit SSD1306@^2.5.13
    robtillaart/CRC@^1.0.3
build_flags =
  ${env.build_flags}
  -D PIN_SDA_XBOX=18 # Wire, fixed in hardware
  -D PIN_SCL_XBOX=19 # Wire, fixed in hardware
  -D PIN_SDA_DISP=17 # Wire1, fixed in hardware
  -D PIN_SCL_DISP=16 # Wire1, fixed in hardware
  -D SERIAL_BAUD=115200

[env:teensy40]
extends = teensy_base
board = teensy40

[env:teensy41]
extends = teensy_base
board = teensy41
